language: ruby
rvm:
  - ruby-2.2.3
  - ruby-head
cache: bundler
sudo: false
notifications:
  email: false
before_script: bundle list
script:
  - bundle exec rake spec
  - bundle exec rake build
deploy:
  - provider: releases
    api_key:
      secure: CbTY7GoUkGKpkjN405/3RifWF6c66ooYODbrmNIuGIBiO5oW8V6ZrxjHHqJZN/dFkpoI/y2Yf9AW0TImfg4fzRsWB4wyMRBWGSbHRoYuYkvBWTwFI1fjX9uBNnDguQ5QF7c6ErI0QRECsGbENRI2iVZFG3arwAlD3d2THcLRp/0=
    file: pkg/wonko_the_sane-*.gem
    on:
      repo: MMCWonko/WonkoTheSane
      tags: true
      rvm: ruby-2.2.3
    skip_cleanup: true
