language: ruby
rvm:
- ruby-2.2.3
- ruby-head

cache: bundler
sudo: false
notifications:
  email: false

before_script: bundle list
script:
- bundle exec rake spec

addons:
  code_climate:
    repo_token:
      secure: EA7KxZyVAE7aQUm4z+4WUoZLuL6gU2cgjn2aqf3HzWDZ3noZdjHhq1qSMBKVuekw7WyTKlg30XLsSQoktLWge9LFLJjRTyAPDulknRmQ91tFcsMXj1FtE+IeT9HGcrCjFvMvMfsO3qQOT9PhDd9PXdusY3OAp+bL3jHqyuVeWG8=
